//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace StyleCop.Analyzers.LayoutRules {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LayoutResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LayoutResources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StyleCop.Analyzers.LayoutRules.LayoutResources", typeof(LayoutResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Align braces に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1500CodeFix {
            get {
                return ResourceManager.GetString("SA1500CodeFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The opening or closing brace within a C# statement, element, or expression is not placed on its own line. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1500Description {
            get {
                return ResourceManager.GetString("SA1500Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Braces for multi-line statements should not share line に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1500MessageFormat {
            get {
                return ResourceManager.GetString("SA1500MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Braces for multi-line statements should not share line に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1500Title {
            get {
                return ResourceManager.GetString("SA1500Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Expand single line block に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1501CodeFix {
            get {
                return ResourceManager.GetString("SA1501CodeFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Expand all single line blocks に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1501CodeFixAll {
            get {
                return ResourceManager.GetString("SA1501CodeFixAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A C# statement containing opening and closing braces is written completely on a single line. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1501Description {
            get {
                return ResourceManager.GetString("SA1501Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Statement should not be on a single line に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1501MessageFormat {
            get {
                return ResourceManager.GetString("SA1501MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Statement should not be on a single line に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1501Title {
            get {
                return ResourceManager.GetString("SA1501Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Expand element に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1502CodeFix {
            get {
                return ResourceManager.GetString("SA1502CodeFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A C# element containing opening and closing braces is written completely on a single line. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1502Description {
            get {
                return ResourceManager.GetString("SA1502Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Element should not be on a single line に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1502MessageFormat {
            get {
                return ResourceManager.GetString("SA1502MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Element should not be on a single line に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1502Title {
            get {
                return ResourceManager.GetString("SA1502Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Wrap with braces に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1503CodeFix {
            get {
                return ResourceManager.GetString("SA1503CodeFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The opening and closing braces for a C# statement have been omitted. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1503Description {
            get {
                return ResourceManager.GetString("SA1503Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Braces should not be omitted に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1503MessageFormat {
            get {
                return ResourceManager.GetString("SA1503MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Braces should not be omitted に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1503Title {
            get {
                return ResourceManager.GetString("SA1503Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reformat accessors to multiple lines style に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1504CodeFixMultipleLines {
            get {
                return ResourceManager.GetString("SA1504CodeFixMultipleLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reformat accessors to single line style に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1504CodeFixSingleLine {
            get {
                return ResourceManager.GetString("SA1504CodeFixSingleLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Within a C# property, indexer or event, at least one of the child accessors is written on a single line, and at least one of the child accessors is written across multiple lines. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1504Description {
            get {
                return ResourceManager.GetString("SA1504Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   All accessors should be single-line or multi-line に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1504MessageFormat {
            get {
                return ResourceManager.GetString("SA1504MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   All accessors should be single-line or multi-line に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1504Title {
            get {
                return ResourceManager.GetString("SA1504Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove blank lines following this brace に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1505CodeFix {
            get {
                return ResourceManager.GetString("SA1505CodeFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An opening brace within a C# element, statement, or expression is followed by a blank line. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1505Description {
            get {
                return ResourceManager.GetString("SA1505Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An opening brace should not be followed by a blank line に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1505MessageFormat {
            get {
                return ResourceManager.GetString("SA1505MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Opening braces should not be followed by blank line に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1505Title {
            get {
                return ResourceManager.GetString("SA1505Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove blank line(s) after documentation header に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1506CodeFix {
            get {
                return ResourceManager.GetString("SA1506CodeFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An element documentation header above a C# element is followed by a blank line. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1506Description {
            get {
                return ResourceManager.GetString("SA1506Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Element documentation headers should not be followed by blank line に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1506MessageFormat {
            get {
                return ResourceManager.GetString("SA1506MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Element documentation headers should not be followed by blank line に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1506Title {
            get {
                return ResourceManager.GetString("SA1506Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove multiple blank lines に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1507CodeFix {
            get {
                return ResourceManager.GetString("SA1507CodeFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The C# code contains multiple blank lines in a row. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1507Description {
            get {
                return ResourceManager.GetString("SA1507Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Code should not contain multiple blank lines in a row に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1507MessageFormat {
            get {
                return ResourceManager.GetString("SA1507MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Code should not contain multiple blank lines in a row に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1507Title {
            get {
                return ResourceManager.GetString("SA1507Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove blank lines preceding this brace に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1508CodeFix {
            get {
                return ResourceManager.GetString("SA1508CodeFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A closing brace within a C# element, statement, or expression is preceded by a blank line. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1508Description {
            get {
                return ResourceManager.GetString("SA1508Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A closing brace should not be preceded by a blank line に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1508MessageFormat {
            get {
                return ResourceManager.GetString("SA1508MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Closing braces should not be preceded by blank line に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1508Title {
            get {
                return ResourceManager.GetString("SA1508Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove blank lines preceding this brace に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1509CodeFix {
            get {
                return ResourceManager.GetString("SA1509CodeFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An opening brace within a C# element, statement, or expression is preceded by a blank line. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1509Description {
            get {
                return ResourceManager.GetString("SA1509Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Opening braces should not be preceded by blank line に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1509MessageFormat {
            get {
                return ResourceManager.GetString("SA1509MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Opening braces should not be preceded by blank line に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1509Title {
            get {
                return ResourceManager.GetString("SA1509Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove blank line before chained statement に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1510CodeFix {
            get {
                return ResourceManager.GetString("SA1510CodeFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Chained C# statements are separated by a blank line. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1510Description {
            get {
                return ResourceManager.GetString("SA1510Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos;{0}&apos; statement should not be preceded by a blank line に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1510MessageFormat {
            get {
                return ResourceManager.GetString("SA1510MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Chained statement blocks should not be preceded by blank line に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1510Title {
            get {
                return ResourceManager.GetString("SA1510Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove blank line before while に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1511CodeFix {
            get {
                return ResourceManager.GetString("SA1511CodeFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The while footer at the bottom of a do-while statement is separated from the statement by a blank line. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1511Description {
            get {
                return ResourceManager.GetString("SA1511Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   While-do footer should not be preceded by blank line に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1511MessageFormat {
            get {
                return ResourceManager.GetString("SA1511MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   While-do footer should not be preceded by blank line に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1511Title {
            get {
                return ResourceManager.GetString("SA1511Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove blank line after comment に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1512CodeFix {
            get {
                return ResourceManager.GetString("SA1512CodeFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A single-line comment within C# code is followed by a blank line. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1512Description {
            get {
                return ResourceManager.GetString("SA1512Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Single-line comments should not be followed by blank line に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1512MessageFormat {
            get {
                return ResourceManager.GetString("SA1512MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Single-line comments should not be followed by blank line に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1512Title {
            get {
                return ResourceManager.GetString("SA1512Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Insert blank line after brace に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1513CodeFix {
            get {
                return ResourceManager.GetString("SA1513CodeFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A closing brace within a C# element, statement, or expression is not followed by a blank line. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1513Description {
            get {
                return ResourceManager.GetString("SA1513Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Closing brace should be followed by blank line に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1513MessageFormat {
            get {
                return ResourceManager.GetString("SA1513MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Closing brace should be followed by blank line に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1513Title {
            get {
                return ResourceManager.GetString("SA1513Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Insert blank line before documentation header に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1514CodeFix {
            get {
                return ResourceManager.GetString("SA1514CodeFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An element documentation header above a C# element is not preceded by a blank line. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1514Description {
            get {
                return ResourceManager.GetString("SA1514Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Element documentation header should be preceded by blank line に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1514MessageFormat {
            get {
                return ResourceManager.GetString("SA1514MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Element documentation header should be preceded by blank line に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1514Title {
            get {
                return ResourceManager.GetString("SA1514Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Insert blank line before comment に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1515CodeFix {
            get {
                return ResourceManager.GetString("SA1515CodeFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A single-line comment within C# code is not preceded by a blank line. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1515Description {
            get {
                return ResourceManager.GetString("SA1515Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Single-line comment should be preceded by blank line に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1515MessageFormat {
            get {
                return ResourceManager.GetString("SA1515MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Single-line comment should be preceded by blank line に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1515Title {
            get {
                return ResourceManager.GetString("SA1515Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fix blank lines に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1516CodeFixAll {
            get {
                return ResourceManager.GetString("SA1516CodeFixAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Insert new line に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1516CodeFixInsert {
            get {
                return ResourceManager.GetString("SA1516CodeFixInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove blank line に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1516CodeFixRemove {
            get {
                return ResourceManager.GetString("SA1516CodeFixRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Adjacent C# elements are not separated by a blank line. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1516Description {
            get {
                return ResourceManager.GetString("SA1516Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Adjacent using directives should not be separated by a blank line. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1516DescriptionOmit {
            get {
                return ResourceManager.GetString("SA1516DescriptionOmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Adjacent using directives should be separated by a blank line. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1516DescriptionRequire {
            get {
                return ResourceManager.GetString("SA1516DescriptionRequire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Elements should be separated by blank line に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1516MessageFormat {
            get {
                return ResourceManager.GetString("SA1516MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Using directives should not be separated by blank line に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1516MessageFormatOmit {
            get {
                return ResourceManager.GetString("SA1516MessageFormatOmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Using directives should be separated by blank line に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1516MessageFormatRequire {
            get {
                return ResourceManager.GetString("SA1516MessageFormatRequire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Elements should be separated by blank line に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1516Title {
            get {
                return ResourceManager.GetString("SA1516Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove blank lines at the start of the file に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1517CodeFix {
            get {
                return ResourceManager.GetString("SA1517CodeFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The code file has blank lines at the start. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1517Description {
            get {
                return ResourceManager.GetString("SA1517Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Code should not contain blank lines at start of file に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1517MessageFormat {
            get {
                return ResourceManager.GetString("SA1517MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Code should not contain blank lines at start of file に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1517Title {
            get {
                return ResourceManager.GetString("SA1517Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fix whitespace at the end of the file に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1518CodeFix {
            get {
                return ResourceManager.GetString("SA1518CodeFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Code should not contain blank lines at the end of the file. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1518DescriptionAllow {
            get {
                return ResourceManager.GetString("SA1518DescriptionAllow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File may not end with a newline character. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1518DescriptionOmit {
            get {
                return ResourceManager.GetString("SA1518DescriptionOmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File is required to end with a single newline character. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1518DescriptionRequire {
            get {
                return ResourceManager.GetString("SA1518DescriptionRequire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Code should not contain blank lines at the end of the file に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1518MessageFormatAllow {
            get {
                return ResourceManager.GetString("SA1518MessageFormatAllow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File may not end with a newline character に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1518MessageFormatOmit {
            get {
                return ResourceManager.GetString("SA1518MessageFormatOmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File is required to end with a single newline character に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1518MessageFormatRequire {
            get {
                return ResourceManager.GetString("SA1518MessageFormatRequire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Use line endings correctly at end of file に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1518Title {
            get {
                return ResourceManager.GetString("SA1518Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The opening and closing braces for a multi-line C# statement have been omitted. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1519Description {
            get {
                return ResourceManager.GetString("SA1519Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Braces should not be omitted from multi-line child statement に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1519MessageFormat {
            get {
                return ResourceManager.GetString("SA1519MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Braces should not be omitted from multi-line child statement に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1519Title {
            get {
                return ResourceManager.GetString("SA1519Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The opening and closing braces of a chained if/else if/else construct were included for some clauses, but omitted for others. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1520Description {
            get {
                return ResourceManager.GetString("SA1520Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Use braces consistently に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1520MessageFormat {
            get {
                return ResourceManager.GetString("SA1520MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Use braces consistently に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1520Title {
            get {
                return ResourceManager.GetString("SA1520Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   波カッコが省略されています に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SX1503Description {
            get {
                return ResourceManager.GetString("SX1503Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   return; break; continu;以外で波カッコは省略できません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SX1503MessageFormat {
            get {
                return ResourceManager.GetString("SX1503MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   波カッコは省略できません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SX1503Title {
            get {
                return ResourceManager.GetString("SX1503Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   三項演算子をネストすることは出来ません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SX1580Description {
            get {
                return ResourceManager.GetString("SX1580Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   三項演算子をネストすることは出来ません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SX1580MessageFormat {
            get {
                return ResourceManager.GetString("SX1580MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   三項演算子をネストすることは出来ません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SX1580Title {
            get {
                return ResourceManager.GetString("SX1580Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   IFディレクティブを使用することは出来ません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SX1581Description {
            get {
                return ResourceManager.GetString("SX1581Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   IFディレクティブを使用することは出来ません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SX1581MessageFormat {
            get {
                return ResourceManager.GetString("SX1581MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   IFディレクティブを使用することは出来ません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SX1581Title {
            get {
                return ResourceManager.GetString("SX1581Title", resourceCulture);
            }
        }
    }
}
