//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace StyleCop.Analyzers.NamingRules {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class NamingResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NamingResources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StyleCop.Analyzers.NamingRules.NamingResources", typeof(NamingResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Rename To &apos;{0}&apos; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RenameToCodeFix {
            get {
                return ResourceManager.GetString("RenameToCodeFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The name of a C# element does not begin with an upper-case letter. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1300Description {
            get {
                return ResourceManager.GetString("SA1300Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Element &apos;{0}&apos; should begin with an uppercase letter に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1300MessageFormat {
            get {
                return ResourceManager.GetString("SA1300MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Element should begin with upper-case letter に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1300Title {
            get {
                return ResourceManager.GetString("SA1300Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There are currently no situations in which this rule will fire. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1301Description {
            get {
                return ResourceManager.GetString("SA1301Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Element should begin with lower-case letter に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1301MessageFormat {
            get {
                return ResourceManager.GetString("SA1301MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Element should begin with lower-case letter に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1301Title {
            get {
                return ResourceManager.GetString("SA1301Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Prefix interface name with &apos;I&apos; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1302CodeFix {
            get {
                return ResourceManager.GetString("SA1302CodeFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The name of a C# interface does not begin with the capital letter I. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1302Description {
            get {
                return ResourceManager.GetString("SA1302Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Interface names should begin with I に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1302MessageFormat {
            get {
                return ResourceManager.GetString("SA1302MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Interface names should begin with I に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1302Title {
            get {
                return ResourceManager.GetString("SA1302Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The name of a constant C# field should begin with an upper-case letter. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1303Description {
            get {
                return ResourceManager.GetString("SA1303Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Const field names should begin with upper-case letter に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1303MessageFormat {
            get {
                return ResourceManager.GetString("SA1303MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Const field names should begin with upper-case letter に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1303Title {
            get {
                return ResourceManager.GetString("SA1303Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The name of a non-private readonly C# field should being with an upper-case letter. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1304Description {
            get {
                return ResourceManager.GetString("SA1304Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Non-private readonly fields should begin with upper-case letter に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1304MessageFormat {
            get {
                return ResourceManager.GetString("SA1304MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Non-private readonly fields should begin with upper-case letter に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1304Title {
            get {
                return ResourceManager.GetString("SA1304Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The name of a field or variable in C# uses Hungarian notation. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1305Description {
            get {
                return ResourceManager.GetString("SA1305Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} &apos;{1}&apos; should not use Hungarian notation に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1305MessageFormat {
            get {
                return ResourceManager.GetString("SA1305MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Field names should not use Hungarian notation に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1305Title {
            get {
                return ResourceManager.GetString("SA1305Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The name of a field in C# does not begin with a lower-case letter. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1306Description {
            get {
                return ResourceManager.GetString("SA1306Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Field &apos;{0}&apos; should begin with lower-case letter に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1306MessageFormat {
            get {
                return ResourceManager.GetString("SA1306MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Field names should begin with lower-case letter に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1306Title {
            get {
                return ResourceManager.GetString("SA1306Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The name of a public or internal field in C# does not begin with an upper-case letter. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1307Description {
            get {
                return ResourceManager.GetString("SA1307Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Field &apos;{0}&apos; should begin with upper-case letter に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1307MessageFormat {
            get {
                return ResourceManager.GetString("SA1307MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Accessible fields should begin with upper-case letter に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1307Title {
            get {
                return ResourceManager.GetString("SA1307Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A field name in C# is prefixed with &apos;m_&apos;, &apos;s_&apos;, or &apos;t_&apos;. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1308Description {
            get {
                return ResourceManager.GetString("SA1308Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Field &apos;{0}&apos; should not begin with the prefix &apos;{1}&apos; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1308MessageFormat {
            get {
                return ResourceManager.GetString("SA1308MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Variable names should not be prefixed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1308Title {
            get {
                return ResourceManager.GetString("SA1308Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A field name in C# begins with an underscore. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1309Description {
            get {
                return ResourceManager.GetString("SA1309Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Field &apos;{0}&apos; should not begin with an underscore に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1309MessageFormat {
            get {
                return ResourceManager.GetString("SA1309MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Field names should not begin with underscore に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1309Title {
            get {
                return ResourceManager.GetString("SA1309Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A field name in C# contains an underscore. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1310Description {
            get {
                return ResourceManager.GetString("SA1310Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Field &apos;{0}&apos; should not contain an underscore に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1310MessageFormat {
            get {
                return ResourceManager.GetString("SA1310MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Field names should not contain underscore に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1310Title {
            get {
                return ResourceManager.GetString("SA1310Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The name of a static readonly field does not begin with an upper-case letter. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1311Description {
            get {
                return ResourceManager.GetString("SA1311Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Static readonly fields should begin with upper-case letter に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1311MessageFormat {
            get {
                return ResourceManager.GetString("SA1311MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Static readonly fields should begin with upper-case letter に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1311Title {
            get {
                return ResourceManager.GetString("SA1311Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The name of a variable in C# does not begin with a lower-case letter. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1312Description {
            get {
                return ResourceManager.GetString("SA1312Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Variable &apos;{0}&apos; should begin with lower-case letter に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1312MessageFormat {
            get {
                return ResourceManager.GetString("SA1312MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Variable names should begin with lower-case letter に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1312Title {
            get {
                return ResourceManager.GetString("SA1312Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The name of a parameter in C# does not begin with a lower-case letter. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1313Description {
            get {
                return ResourceManager.GetString("SA1313Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Parameter &apos;{0}&apos; should begin with lower-case letter に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1313MessageFormat {
            get {
                return ResourceManager.GetString("SA1313MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Parameter names should begin with lower-case letter に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1313Title {
            get {
                return ResourceManager.GetString("SA1313Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Prefix type parameter name with &apos;T&apos; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1314CodeFix {
            get {
                return ResourceManager.GetString("SA1314CodeFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The name of a C# type parameter does not begin with the capital letter T. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1314Description {
            get {
                return ResourceManager.GetString("SA1314Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Type parameter names should begin with T に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1314MessageFormat {
            get {
                return ResourceManager.GetString("SA1314MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Type parameter names should begin with T に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1314Title {
            get {
                return ResourceManager.GetString("SA1314Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Correct tuple element name casing に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1316CodeFix {
            get {
                return ResourceManager.GetString("SA1316CodeFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Element names within a tuple type should have the correct casing. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1316Description {
            get {
                return ResourceManager.GetString("SA1316Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tuple element names should use correct casing に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1316MessageFormat {
            get {
                return ResourceManager.GetString("SA1316MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tuple element names should use correct casing に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1316Title {
            get {
                return ResourceManager.GetString("SA1316Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A field name in C# does not begin with an underscore. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SX1309Description {
            get {
                return ResourceManager.GetString("SX1309Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Field &apos;{0}&apos; should begin with an underscore に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SX1309MessageFormat {
            get {
                return ResourceManager.GetString("SX1309MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A static field name in C# does not begin with an underscore. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SX1309SDescription {
            get {
                return ResourceManager.GetString("SX1309SDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Static field &apos;{0}&apos; should begin with an underscore に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SX1309SMessageFormat {
            get {
                return ResourceManager.GetString("SX1309SMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Static field names should begin with underscore に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SX1309STitle {
            get {
                return ResourceManager.GetString("SX1309STitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Field names should begin with underscore に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SX1309Title {
            get {
                return ResourceManager.GetString("SX1309Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Not used に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SX1313Description {
            get {
                return ResourceManager.GetString("SX1313Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Not used に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SX1313MessageFormat {
            get {
                return ResourceManager.GetString("SX1313MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Not used に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SX1313Title {
            get {
                return ResourceManager.GetString("SX1313Title", resourceCulture);
            }
        }
    }
}
