//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace StyleCop.Analyzers.DocumentationRules {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DocumentationResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DocumentationResources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StyleCop.Analyzers.DocumentationRules.DocumentationResources", typeof(DocumentationResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Generate constructor documentation に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConstructorDocumentationCodeFix {
            get {
                return ResourceManager.GetString("ConstructorDocumentationCodeFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Generate destructor documentation に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DestructorDocumentationCodeFix {
            get {
                return ResourceManager.GetString("DestructorDocumentationCodeFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Finalizes an instance of the  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DestructorStandardTextFirstPart {
            get {
                return ResourceManager.GetString("DestructorStandardTextFirstPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///    class. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DestructorStandardTextSecondPart {
            get {
                return ResourceManager.GetString("DestructorStandardTextSecondPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Inherit documentation に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InheritdocCodeFix {
            get {
                return ResourceManager.GetString("InheritdocCodeFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Generate method documentation に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MethodDocumentationCodeFix {
            get {
                return ResourceManager.GetString("MethodDocumentationCodeFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Initializes a new instance of the  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NonPrivateConstructorStandardTextFirstPart {
            get {
                return ResourceManager.GetString("NonPrivateConstructorStandardTextFirstPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///    {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NonPrivateConstructorStandardTextSecondPart {
            get {
                return ResourceManager.GetString("NonPrivateConstructorStandardTextSecondPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The parameter is not used. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ParameterNotUsed {
            get {
                return ResourceManager.GetString("ParameterNotUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Prevents a default instance of the  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PrivateConstructorStandardTextFirstPart {
            get {
                return ResourceManager.GetString("PrivateConstructorStandardTextFirstPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///    {0} from being created に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PrivateConstructorStandardTextSecondPart {
            get {
                return ResourceManager.GetString("PrivateConstructorStandardTextSecondPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add standard text に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PropertySummaryStartTextCodeFix {
            get {
                return ResourceManager.GetString("PropertySummaryStartTextCodeFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A C# code element is missing a documentation header. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1600Description {
            get {
                return ResourceManager.GetString("SA1600Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Elements should be documented に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1600MessageFormat {
            get {
                return ResourceManager.GetString("SA1600MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Elements should be documented に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1600Title {
            get {
                return ResourceManager.GetString("SA1600Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A C# partial element is missing a documentation header. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1601Description {
            get {
                return ResourceManager.GetString("SA1601Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Partial elements should be documented に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1601MessageFormat {
            get {
                return ResourceManager.GetString("SA1601MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Partial elements should be documented に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1601Title {
            get {
                return ResourceManager.GetString("SA1601Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An item within a C# enumeration is missing an Xml documentation header. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1602Description {
            get {
                return ResourceManager.GetString("SA1602Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enumeration items should be documented に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1602MessageFormat {
            get {
                return ResourceManager.GetString("SA1602MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enumeration items should be documented に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1602Title {
            get {
                return ResourceManager.GetString("SA1602Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The XML within a C# element’s document header is badly formed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1603Description {
            get {
                return ResourceManager.GetString("SA1603Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The documentation header is composed of invalid XML: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1603MessageFormat {
            get {
                return ResourceManager.GetString("SA1603MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Documentation should contain valid XML に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1603Title {
            get {
                return ResourceManager.GetString("SA1603Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The XML header documentation for a C# element is missing a &lt;summary&gt; tag. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1604Description {
            get {
                return ResourceManager.GetString("SA1604Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Element documentation should have summary に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1604MessageFormat {
            get {
                return ResourceManager.GetString("SA1604MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Element documentation should have summary に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1604Title {
            get {
                return ResourceManager.GetString("SA1604Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The &lt;summary&gt; or &lt;content&gt; tag within the documentation header for a C# code element is missing or empty. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1605Description {
            get {
                return ResourceManager.GetString("SA1605Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Partial element documentation should have summary に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1605MessageFormat {
            get {
                return ResourceManager.GetString("SA1605MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Partial element documentation should have summary に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1605Title {
            get {
                return ResourceManager.GetString("SA1605Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The &lt;summary&gt; tag within the documentation header for a C# code element is empty. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1606Description {
            get {
                return ResourceManager.GetString("SA1606Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Element documentation should have summary text に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1606MessageFormat {
            get {
                return ResourceManager.GetString("SA1606MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Element documentation should have summary text に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1606Title {
            get {
                return ResourceManager.GetString("SA1606Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The &lt;summary&gt; or &lt;content&gt; tag within the documentation header for a C# code element is empty. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1607Description {
            get {
                return ResourceManager.GetString("SA1607Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Partial element documentation should have summary text に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1607MessageFormat {
            get {
                return ResourceManager.GetString("SA1607MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Partial element documentation should have summary text に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1607Title {
            get {
                return ResourceManager.GetString("SA1607Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The &lt;summary&gt; tag within an element&apos;s XML header documentation contains the default text generated by Visual Studio during the creation of the element. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1608Description {
            get {
                return ResourceManager.GetString("SA1608Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Element documentation should not have default summary に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1608MessageFormat {
            get {
                return ResourceManager.GetString("SA1608MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Element documentation should not have default summary に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1608Title {
            get {
                return ResourceManager.GetString("SA1608Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The XML header documentation for a C# property does not contain a &lt;value&gt; tag. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1609Description {
            get {
                return ResourceManager.GetString("SA1609Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Property documentation should have value に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1609MessageFormat {
            get {
                return ResourceManager.GetString("SA1609MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Document value from summary に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1609SA1610CodeFix {
            get {
                return ResourceManager.GetString("SA1609SA1610CodeFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Property documentation should have value に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1609Title {
            get {
                return ResourceManager.GetString("SA1609Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The XML header documentation for a C# property contains an empty &lt;value&gt; tag. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1610Description {
            get {
                return ResourceManager.GetString("SA1610Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Property documentation should have value text に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1610MessageFormat {
            get {
                return ResourceManager.GetString("SA1610MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Property documentation should have value text に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1610Title {
            get {
                return ResourceManager.GetString("SA1610Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A C# method, constructor, delegate or indexer element is missing documentation for one or more of its parameters. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1611Description {
            get {
                return ResourceManager.GetString("SA1611Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The documentation for parameter &apos;{0}&apos; is missing に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1611MessageFormat {
            get {
                return ResourceManager.GetString("SA1611MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Element parameters should be documented に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1611Title {
            get {
                return ResourceManager.GetString("SA1611Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The documentation describing the parameters to a C# method, constructor, delegate or indexer element does not match the actual parameters on the element. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1612Description {
            get {
                return ResourceManager.GetString("SA1612Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The parameter &apos;{0}&apos; does not exist に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1612MissingParamForDocumentationMessageFormat {
            get {
                return ResourceManager.GetString("SA1612MissingParamForDocumentationMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The parameter documentation for &apos;{0}&apos; should be at position {1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1612ParamWrongOrderMessageFormat {
            get {
                return ResourceManager.GetString("SA1612ParamWrongOrderMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Element parameter documentation should match element parameters に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1612Title {
            get {
                return ResourceManager.GetString("SA1612Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A &lt;param&gt; tag within a C# element&apos;s documentation header is missing a name attribute containing the name of the parameter. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1613Description {
            get {
                return ResourceManager.GetString("SA1613Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Element parameter documentation should declare parameter name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1613MessageFormat {
            get {
                return ResourceManager.GetString("SA1613MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Element parameter documentation should declare parameter name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1613Title {
            get {
                return ResourceManager.GetString("SA1613Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A &lt;param&gt; tag within a C# element&apos;s documentation header is empty. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1614Description {
            get {
                return ResourceManager.GetString("SA1614Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Element parameter documentation should have text に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1614MessageFormat {
            get {
                return ResourceManager.GetString("SA1614MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Element parameter documentation should have text に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1614Title {
            get {
                return ResourceManager.GetString("SA1614Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A C# element is missing documentation for its return value. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1615Description {
            get {
                return ResourceManager.GetString("SA1615Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Element return value should be documented に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1615MessageFormat {
            get {
                return ResourceManager.GetString("SA1615MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Document return value に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1615SA1616CodeFix {
            get {
                return ResourceManager.GetString("SA1615SA1616CodeFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Element return value should be documented に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1615Title {
            get {
                return ResourceManager.GetString("SA1615Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The &lt;returns&gt; tag within a C# element&apos;s documentation header is empty. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1616Description {
            get {
                return ResourceManager.GetString("SA1616Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Element return value documentation should have text に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1616MessageFormat {
            get {
                return ResourceManager.GetString("SA1616MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Element return value documentation should have text に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1616Title {
            get {
                return ResourceManager.GetString("SA1616Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove &lt;returns&gt; XML comment に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1617CodeFix {
            get {
                return ResourceManager.GetString("SA1617CodeFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A C# code element does not contain a return value, or returns void, but the documentation header for the element contains a &lt;returns&gt; tag. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1617Description {
            get {
                return ResourceManager.GetString("SA1617Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Void return value should not be documented に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1617MessageFormat {
            get {
                return ResourceManager.GetString("SA1617MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Void return value should not be documented に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1617Title {
            get {
                return ResourceManager.GetString("SA1617Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A generic C# element is missing documentation for one or more of its generic type parameters. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1618Description {
            get {
                return ResourceManager.GetString("SA1618Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The documentation for type parameter &apos;{0}&apos; is missing に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1618MessageFormat {
            get {
                return ResourceManager.GetString("SA1618MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Generic type parameters should be documented に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1618Title {
            get {
                return ResourceManager.GetString("SA1618Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A generic, partial C# element is missing documentation for one or more of its generic type parameters, and the documentation for the element contains a &lt;summary&gt; tag. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1619Description {
            get {
                return ResourceManager.GetString("SA1619Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The documentation for type parameter &apos;{0}&apos; is missing に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1619MessageFormat {
            get {
                return ResourceManager.GetString("SA1619MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Generic type parameters should be documented partial class に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1619Title {
            get {
                return ResourceManager.GetString("SA1619Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The &lt;typeparam&gt; tags within the Xml header documentation for a generic C# element do not match the generic type parameters on the element. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1620Description {
            get {
                return ResourceManager.GetString("SA1620Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The type parameter &apos;{0}&apos; does not exist. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1620MissingMessageFormat {
            get {
                return ResourceManager.GetString("SA1620MissingMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Generic type parameter documentation should match type parameters に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1620Title {
            get {
                return ResourceManager.GetString("SA1620Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The type parameter documentation for &apos;{0}&apos; should be at position {1}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1620WrongOrderMessageFormat {
            get {
                return ResourceManager.GetString("SA1620WrongOrderMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A &lt;typeparam&gt; tag within the XML header documentation for a generic C# element is missing a name attribute, or contains an empty name attribute. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1621Description {
            get {
                return ResourceManager.GetString("SA1621Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Generic type parameter documentation should declare parameter name. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1621MessageFormat {
            get {
                return ResourceManager.GetString("SA1621MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Generic type parameter documentation should declare parameter name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1621Title {
            get {
                return ResourceManager.GetString("SA1621Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A &lt;typeparam&gt; tag within the Xml header documentation for a generic C# element is empty. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1622Description {
            get {
                return ResourceManager.GetString("SA1622Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Generic type parameter documentation should have text. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1622MessageFormat {
            get {
                return ResourceManager.GetString("SA1622MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Generic type parameter documentation should have text に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1622Title {
            get {
                return ResourceManager.GetString("SA1622Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The documentation text within a C# property’s &lt;summary&gt; tag does not match the accessors within the property. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1623Description {
            get {
                return ResourceManager.GetString("SA1623Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The property&apos;s documentation summary text should begin with: &apos;{0}&apos; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1623MessageFormat {
            get {
                return ResourceManager.GetString("SA1623MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Property summary documentation should match accessors に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1623Title {
            get {
                return ResourceManager.GetString("SA1623Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The documentation text within a C# property’s &lt;summary&gt; tag takes into account all of the accessors within the property, but one of the accessors has limited access. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1624Description {
            get {
                return ResourceManager.GetString("SA1624Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Because the property only contains a visible {0} accessor, the documentation summary text should begin with &apos;{1}&apos;. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1624MessageFormat {
            get {
                return ResourceManager.GetString("SA1624MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Property summary documentation should omit accessor with restricted access に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1624Title {
            get {
                return ResourceManager.GetString("SA1624Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The Xml documentation for a C# element contains two or more identical entries, indicating that the documentation has been copied and pasted. This can sometimes indicate invalid or poorly written documentation. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1625Description {
            get {
                return ResourceManager.GetString("SA1625Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Element documentation should not be copied and pasted に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1625MessageFormat {
            get {
                return ResourceManager.GetString("SA1625MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Element documentation should not be copied and pasted に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1625Title {
            get {
                return ResourceManager.GetString("SA1625Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Convert to line comment に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1626CodeFix {
            get {
                return ResourceManager.GetString("SA1626CodeFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The C# code contains a single-line comment which begins with three forward slashes in a row. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1626Description {
            get {
                return ResourceManager.GetString("SA1626Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Single-line comments should not use documentation style slashes に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1626MessageFormat {
            get {
                return ResourceManager.GetString("SA1626MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Single-line comments should not use documentation style slashes に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1626Title {
            get {
                return ResourceManager.GetString("SA1626Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The XML header documentation for a C# code element contains an empty tag. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1627Description {
            get {
                return ResourceManager.GetString("SA1627Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The documentation text within the &apos;{0}&apos; tag should not be empty に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1627MessageFormat {
            get {
                return ResourceManager.GetString("SA1627MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Documentation text should not be empty に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1627Title {
            get {
                return ResourceManager.GetString("SA1627Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A section of the XML header documentation for a C# element does not begin with a capital letter. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1628Description {
            get {
                return ResourceManager.GetString("SA1628Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TODO: Message format に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1628MessageFormat {
            get {
                return ResourceManager.GetString("SA1628MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Documentation text should begin with a capital letter に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1628Title {
            get {
                return ResourceManager.GetString("SA1628Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add period に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1629CodeFix {
            get {
                return ResourceManager.GetString("SA1629CodeFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A section of the XML header documentation for a C# element does not end with a period. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1629Description {
            get {
                return ResourceManager.GetString("SA1629Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Documentation text should end with a period に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1629MessageFormat {
            get {
                return ResourceManager.GetString("SA1629MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Documentation text should end with a period に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1629Title {
            get {
                return ResourceManager.GetString("SA1629Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A section of the XML header documentation for a C# element does not contain any whitespace between words. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1630Description {
            get {
                return ResourceManager.GetString("SA1630Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TODO: Message format に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1630MessageFormat {
            get {
                return ResourceManager.GetString("SA1630MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Documentation text should contain whitespace に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1630Title {
            get {
                return ResourceManager.GetString("SA1630Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A section of the Xml header documentation for a C# element does not contain enough alphabetic characters. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1631Description {
            get {
                return ResourceManager.GetString("SA1631Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TODO: Message format に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1631MessageFormat {
            get {
                return ResourceManager.GetString("SA1631MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Documentation should meet character percentage に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1631Title {
            get {
                return ResourceManager.GetString("SA1631Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A section of the Xml header documentation for a C# element is too short. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1632Description {
            get {
                return ResourceManager.GetString("SA1632Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TODO: Message format に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1632MessageFormat {
            get {
                return ResourceManager.GetString("SA1632MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Documentation text should meet minimum character length に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1632Title {
            get {
                return ResourceManager.GetString("SA1632Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add file header に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1633CodeFix {
            get {
                return ResourceManager.GetString("SA1633CodeFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A C# code file is missing a standard file header. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1633Description {
            get {
                return ResourceManager.GetString("SA1633Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The file header XML is invalid. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1633MessageFormatMalformed {
            get {
                return ResourceManager.GetString("SA1633MessageFormatMalformed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The file header is missing or not located at the top of the file. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1633MessageFormatMissing {
            get {
                return ResourceManager.GetString("SA1633MessageFormatMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File should have header に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1633Title {
            get {
                return ResourceManager.GetString("SA1633Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The file header at the top of a C# code file is missing a copyright tag. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1634Description {
            get {
                return ResourceManager.GetString("SA1634Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The file header should contain a copyright tag. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1634MessageFormat {
            get {
                return ResourceManager.GetString("SA1634MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File header should show copyright に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1634Title {
            get {
                return ResourceManager.GetString("SA1634Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The file header at the top of a C# code file is missing copyright text. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1635Description {
            get {
                return ResourceManager.GetString("SA1635Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File header should have copyright text に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1635MessageFormat {
            get {
                return ResourceManager.GetString("SA1635MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File header should have copyright text に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1635Title {
            get {
                return ResourceManager.GetString("SA1635Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The file header at the top of a C# code file does not contain the appropriate copyright text. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1636Description {
            get {
                return ResourceManager.GetString("SA1636Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The file header copyright text should match the copyright text from the settings. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1636MessageFormat {
            get {
                return ResourceManager.GetString("SA1636MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File header copyright text should match に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1636Title {
            get {
                return ResourceManager.GetString("SA1636Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The file header at the top of a C# code file is missing the file name. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1637Description {
            get {
                return ResourceManager.GetString("SA1637Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File header should contain file name. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1637MessageFormat {
            get {
                return ResourceManager.GetString("SA1637MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File header should contain file name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1637Title {
            get {
                return ResourceManager.GetString("SA1637Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The file attribute within copyright tag of the file header at the top of a C# code file does not contain the name of the file. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1638Description {
            get {
                return ResourceManager.GetString("SA1638Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File header file name documentation should match file name. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1638MessageFormat {
            get {
                return ResourceManager.GetString("SA1638MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File header file name documentation should match file name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1638Title {
            get {
                return ResourceManager.GetString("SA1638Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The file header at the top of a C# code file does not contain a filled-in summary tag. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1639Description {
            get {
                return ResourceManager.GetString("SA1639Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File header should have summary に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1639MessageFormat {
            get {
                return ResourceManager.GetString("SA1639MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File header should have summary に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1639Title {
            get {
                return ResourceManager.GetString("SA1639Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The file header at the top of a C# code file does not contain company name text. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1640Description {
            get {
                return ResourceManager.GetString("SA1640Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The copyright tag should contain a non-empty company attribute. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1640MessageFormat {
            get {
                return ResourceManager.GetString("SA1640MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File header should have valid company text に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1640Title {
            get {
                return ResourceManager.GetString("SA1640Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The file header at the top of a C# code file does not contain the appropriate company name text. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1641Description {
            get {
                return ResourceManager.GetString("SA1641Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The file header company name should match the company name from the settings. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1641MessageFormat {
            get {
                return ResourceManager.GetString("SA1641MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File header company name text should match に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1641Title {
            get {
                return ResourceManager.GetString("SA1641Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The XML documentation header for a C# constructor does not contain the appropriate summary text. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1642Description {
            get {
                return ResourceManager.GetString("SA1642Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Constructor summary documentation should begin with standard text に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1642MessageFormat {
            get {
                return ResourceManager.GetString("SA1642MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add standard text に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1642SA1643CodeFix {
            get {
                return ResourceManager.GetString("SA1642SA1643CodeFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Constructor summary documentation should begin with standard text に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1642Title {
            get {
                return ResourceManager.GetString("SA1642Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The XML documentation header for a C# finalizer does not contain the appropriate summary text. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1643Description {
            get {
                return ResourceManager.GetString("SA1643Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Destructor summary documentation should begin with standard text に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1643MessageFormat {
            get {
                return ResourceManager.GetString("SA1643MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Destructor summary documentation should begin with standard text に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1643Title {
            get {
                return ResourceManager.GetString("SA1643Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A section within the XML documentation header for a C# element contains blank lines. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1644Description {
            get {
                return ResourceManager.GetString("SA1644Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TODO: Message format に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1644MessageFormat {
            get {
                return ResourceManager.GetString("SA1644MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Documentation headers should not contain blank lines に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1644Title {
            get {
                return ResourceManager.GetString("SA1644Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An included XML documentation file does not exist. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1645Description {
            get {
                return ResourceManager.GetString("SA1645Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TODO: Message format に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1645MessageFormat {
            get {
                return ResourceManager.GetString("SA1645MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Included documentation file does not exist に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1645Title {
            get {
                return ResourceManager.GetString("SA1645Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An included XML documentation link contains an invalid path. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1646Description {
            get {
                return ResourceManager.GetString("SA1646Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TODO: Message format に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1646MessageFormat {
            get {
                return ResourceManager.GetString("SA1646MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Included documentation XPath does not exist に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1646Title {
            get {
                return ResourceManager.GetString("SA1646Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An include tag within an XML documentation header does not contain valid file and path attribute. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1647Description {
            get {
                return ResourceManager.GetString("SA1647Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TODO: Message format に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1647MessageFormat {
            get {
                return ResourceManager.GetString("SA1647MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Include node does not contain valid file and path に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1647Title {
            get {
                return ResourceManager.GetString("SA1647Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;inheritdoc&gt; has been used on an element that doesn&apos;t inherit from a base class or implement an interface. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1648Description {
            get {
                return ResourceManager.GetString("SA1648Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   inheritdoc should be used with inheriting class に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1648MessageFormat {
            get {
                return ResourceManager.GetString("SA1648MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   inheritdoc should be used with inheriting class に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1648Title {
            get {
                return ResourceManager.GetString("SA1648Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Rename file to match first type name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1649CodeFix {
            get {
                return ResourceManager.GetString("SA1649CodeFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The file name of a C# code file does not match the first type declared in the file. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1649Description {
            get {
                return ResourceManager.GetString("SA1649Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File name should match first type name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1649MessageFormat {
            get {
                return ResourceManager.GetString("SA1649MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File name should match first type name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1649Title {
            get {
                return ResourceManager.GetString("SA1649Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The element documentation for the element contains one or more spelling mistakes or unrecognized words. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1650Description {
            get {
                return ResourceManager.GetString("SA1650Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TODO: Message format に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1650MessageFormat {
            get {
                return ResourceManager.GetString("SA1650MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Element documentation should be spelled correctly に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1650Title {
            get {
                return ResourceManager.GetString("SA1650Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Finalize placeholder text に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1651CodeFix {
            get {
                return ResourceManager.GetString("SA1651CodeFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The element documentation contains a &lt;placeholder&gt; element. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1651Description {
            get {
                return ResourceManager.GetString("SA1651Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do not use placeholder elements に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1651MessageFormat {
            get {
                return ResourceManager.GetString("SA1651MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do not use placeholder elements に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SA1651Title {
            get {
                return ResourceManager.GetString("SA1651Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Gets に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StartingTextGets {
            get {
                return ResourceManager.GetString("StartingTextGets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Gets or sets に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StartingTextGetsOrSets {
            get {
                return ResourceManager.GetString("StartingTextGetsOrSets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Gets or sets a value indicating whether に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StartingTextGetsOrSetsWhether {
            get {
                return ResourceManager.GetString("StartingTextGetsOrSetsWhether", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Gets a value indicating whether に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StartingTextGetsWhether {
            get {
                return ResourceManager.GetString("StartingTextGetsWhether", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Returns に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StartingTextReturns {
            get {
                return ResourceManager.GetString("StartingTextReturns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Returns a value indicating whether に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StartingTextReturnsWhether {
            get {
                return ResourceManager.GetString("StartingTextReturnsWhether", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sets に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StartingTextSets {
            get {
                return ResourceManager.GetString("StartingTextSets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sets a value indicating whether に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StartingTextSetsWhether {
            get {
                return ResourceManager.GetString("StartingTextSetsWhether", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Initializes static members of the  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StaticConstructorStandardTextFirstPart {
            get {
                return ResourceManager.GetString("StaticConstructorStandardTextFirstPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///    {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StaticConstructorStandardTextSecondPart {
            get {
                return ResourceManager.GetString("StaticConstructorStandardTextSecondPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Not used に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SX1680Description {
            get {
                return ResourceManager.GetString("SX1680Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Not used に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SX1680MessageFormat {
            get {
                return ResourceManager.GetString("SX1680MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Not used に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SX1680Title {
            get {
                return ResourceManager.GetString("SX1680Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TaskReturnElementFirstPart {
            get {
                return ResourceManager.GetString("TaskReturnElementFirstPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///    representing the result of the asynchronous operation. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TaskReturnElementSecondPart {
            get {
                return ResourceManager.GetString("TaskReturnElementSecondPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   class に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TypeTextClass {
            get {
                return ResourceManager.GetString("TypeTextClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   struct に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TypeTextStruct {
            get {
                return ResourceManager.GetString("TypeTextStruct", resourceCulture);
            }
        }
    }
}
